[mongo]
uri= "mongodb://localhost:27017"
db= "QAREALTIME"

[mq]
uri= "amqp://admin:admin@192.168.2.125:5672/"
exchange= "QAORDER_ROUTER"
routing_key= "150083"

[common]
wsuri= "ws://192.168.2.124:7988"
#wsuri= "ws://127.0.0.1:5000/ws/signal"
user_name= "150083"
password= "980817"
broker= "simnow"
